language: node_js
node_js:
- node
- '6'
- '5'
deploy:
  provider: heroku
  api_key:
    secure: USXQaB0Yi8z/7k9IZ6mmDwwWjjQMmrHB9l80qCywUO9rsUH2krhs7MvObXIYX4PAbxKg2YDjOxYm5PJAZbvPv4EluNlHAwO+Mo80A1qCC8djeuNcinNCtSFRew3kEAoyaia8fENJjWjqk2zKxJwHQdU3CqHGZwOvGMnN5/yJEcjHxResaIivg9saSEaPcypPsXgys4Nuhe3ddNBdYQ5ylFa47TWhsTJwpWcPUcWHZdZQ4YQjuEeEm2C5MeEVehg5ndGvvwIZYD33hEb4T5MknmnNtX7dPZ1YZ+8YB5DgF+yEHlvtThhnBXLWiZ7ysuVxWj0D2wBDTiCIKGqWXF5s+e+mIy0kJGyaMUDko5iFvaj9YkwnHh+fvnPCduAj8uqf7jf0CbL2g/zRPEpGaBXWfB61CGraE1iLmKm3IMLa/vSco4fhLcWobc4bDvq8xs4sOgxo6jTvFGFySshogYBSuifjH9m/C3WguvweDToSz+ulOCFrDHKL8Gd7o1aSoP8vA1Sd6aQNihkZ/GOb//kbaBh38ipG0nbGZnI9xBzzFM7Er30LqqrvqyWHDzahx4grULpu3BYdXx0JaR1XXup5MfqicXsol0eray33N4Hs0l1KI35HaNvTGzTFXikaLEiU2z65qVxw/hvEBScphLlx3dDfrokBdjJvQXk2r9adE5Q=
  app: fast-citadel-97475
  on: master
