sudo: required
language: node_js
node_js:
- node
- '6'
- '4'
services:
  - docker
after_success:
  - yarn install --production
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login --username="${DOCKER_USERNAME}" --password="${DOCKER_PASSWORD}" registry.heroku.com;
    docker build -t registry.heroku.com/mr-jums/web .;
    docker push registry.heroku.com/mr-jums/web;
    fi
