language: node_js
node_js:
- node
- '6'
- '5'
deploy:
  provider: heroku
  api_key:
    secure: PFqvNNKQFCrQIo7o9ZOZMwJXeeyflFnRVO3QWVmGnUksfm14+yTY2/kyESyIuP5PGnolKyGa8pvbr3+PEK5EpEJMSynSSJlWX38KAZ72hwi7+XWpJlCvx7JQlZ4BNkCKlKf2ualHK9h2iX0SA7XF7b3aOjrzbPV3WUsPLEbhwhJFC7d4VmjpsmRk2RyQ4KTsRnnj7gfDW34q3vpekn60A9FCM5tUKxZI4bDemkN3mujNlfYtcGpZ9eTAIouUgZmY4RM+IIjU/pqBzfFQ30T35WVTJF4YJdXfrCP1UAuDvvzc/dWSHGHA2MW/oWtgXf0NKOF1r6V2PORNNNkP1gGCOqZ/gupAdotkJzvptEvhTi56pI6+cCRJnlH2lsXjRdRvWTVvNpXM1hBoWi9DFEncEh3KxlZ4t8UQrmWIxtNsmVTWY5sGWd2zNxXetq5hqzMGh1CpE1rVLruo/5PjRSJXh4n70BePLlBvaZ6VQ9BI2oaGiH4k6BsAfZVa9XpAvZRRthP3T+n6VOyb9tQylHFetWqAEuVfJUdh9/iP2EOv+OPUVHR+IheQ6OtJAx5QPSWQ30XPQSQ2Y6SSs3YZ3DhjL4jZXNjjqCzQTzFxQvSWTyQIpcxVJk6f2unagV9xBE1P86xvJduKC6W/JhcnJAmQyXhiLJ7cugY48UiiDqOUUYA=
  app: fast-citadel-97475
  on:
    repo: bouzuya/mr-jums
