language: node_js
node_js:
- node
- '6'
- '5'
deploy:
  provider: heroku
  api_key:
    secure: r5xQevwclRk5vzw7AyFYKpEygh3pyNDrdrfAnZQMtJukMKVIopF3JgosLkvwP43lh+ByIHziYWFvJmK54dQypZ20Jr9MKwSuusgtkmnoqteGwNLciPIB3GMG9gjQYOxS61NI8+2IynyOeAW9xZJ2jwdH72G2bWZ5cBUi63s8Jnn6Qw53wC4Mgx6GmFaKf69DvL7poRQnEiBmkc8KUCB0HTAwS7hqpIK4EWuKPUodDNeQXisbfIZdhOW4whqnEX9qcPOV7JmN+C/DkIVHlFoXGjz8bhi8VHAOVCrRMOgcOLVnd3ATMhJHhp4hLVih40yuw4zbfNbNkK0FhchC1yGR2eKkSTZTi0ZvnWs20J74GoJkV2nyuUzfv8r/sUSjBNMpoCwoi3lIGg3LGKGeQvnyjWKysGsjRn4j83XO05nLFiCR1v+WFs3WxreOrfedc/F+UeBd9GcP8KhvnKJla9HqkXb7DrDDp65hkOEnOwFvGo424s7o3DWpQsmIDsMbSOGcRs0BcWgCVTbHP43d15J+X4JF3eyoiCdHr6ALpmMfUWicv+HetFB8dgSGiejTOJQ9PD1rkfPmcdqJ0YIJHPbcKwoGBFOIIfJnF81snaagsi6J/164Oj+jymoeCCRB+FPV7JkNEODNhXzWdJqbpI5TTk1bvx/1CmYFjSh1zn6NTuU=
  app: fast-citadel-97475
  on: master
