language: node_js
node_js:
- node
- '6'
- '5'
deploy:
  provider: heroku
  api_key:
    secure: j1BlcgGfsVVhvnHm91gTQG6uWcFGBxnWof2yppkruvOtrQ0Ndzroc7jZiP+eF2TMq8xM88YDxANiN6NLNFo2hRRneX7UQjRiHdcRKt8Ruu387aov/aRmelzZY2k7HXJGxoBET8Pf/U33pYfV0fIrdWeb9k2FMMVz21ZNaS5c2xXvcNriclvUAKYPK4FgQbAewq2WCh6PaTcg5FVOsTqiVUxBJYEMk1YqGmr6eW4xkiWyABYH8+QNegOa58lSZZiNz7slvJPcSf3dIiayjFQuL49NhfQ0ldII+2/51llHtoJ+zOxksDvodHnHIkDKNjBICaPOP+VggWKFj8I7ShPMkz9Y7N1HgMHniMafIdrJ0PFNhiNzq11Nlx91oT7demQhtEYgFE0gIcwMa/m7Rol7yZVK4aJ9DFaF1/2wvluFjYvB0LlIs1vlglcbE2HiehgEGUe+bMTbOZrBZK9okK7TH8rAEV2iZEEWpsEsqT9olRYCKXfJgsMeVMwtnpcf7ytNLO9q58AxGPHGhAu4Xpw1cmEoYSZNT+FLOYn4h6MnOth5YFzNs9Q7uIEoEitYAc5SfYse8P3a4gRSMEY5LBpbVojvqxa6pAA3WJWELRa/7QirZ43Th+F1pbTaq5R0zFoifzDvcZObcWh0v0hEiuCORhXWk5PbnpchN3phBNgcLf8=
  app: fast-citadel-97475
  on:
    repo: bouzuya/mr-jums
