language: node_js
node_js:
- node
- '6'
- '5'
deploy:
  provider: heroku
  api_key:
    secure: OHZ0yK2KU2Xsic6oWckIQWtiFdRNS0vqdUwDr2b4VmRMHW0c5SOj+54I/9TvQXKSH5QcE7TIiOTVQ7oRz9eD4M+SHFR0YcXl/Jz3JkV7Nr1lYwBl26wgfEylhmzzzK231q71MzeWOKpBxXkUDRWGgDuvUbIStHn5hdJYzNHKMN6/Qxv9mie53z2vrMqYnTGyP2O5j9WWMPa2RU9EhNs5cOJQTgtn4t6EEWMkiamPAoZrGJvzs9QACMLibzcWT3uUUubmtQJZyoOHSRbCVB3QLbxdS5LIsa3wUlVI95UCH6cjC2Al0X3aLpjIs9D1xS1s2yPrpOVT0xiT3Zky9CC5EmJlRZ3JohkRwaqTsb1OjyMSYJM+1vrUbWjqTaZdVBsQQWwGV4eMBUj2HD2elWuAOkN8LTFSzvLiay51v2wIEHdmhGePZDnpASdeacrNyiRff3LRKWpumRnpkDMDhmdM2VV2cVpX97awqmqJ6F6s057S1QIh8w/ue2i+UAsoAbPej52f5oPQteL7ZR4ArR96gnyjGgAR0mTq6mwYxa50vZ99pGXIil+ZRRC32XT+QbuyfO72Mx0CdWLW6GBOHWkFINjlkR/rIF37azlRcrE6lzsiajS/aa8foIV/l+6F3GJmvNI/bir5QvnXbPznHxdwfvXkGcVLbvVn0ZQ08VHVZbQ=
  app: fast-citadel-97475
  on:
    repo: bouzuya/mr-jums
