sudo: required
language: node_js
node_js:
- node
- '6'
- '4'
services:
- docker
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login --username="${DOCKER_USERNAME}" --password="${DOCKER_PASSWORD}" registry.heroku.com;
  docker build -t registry.heroku.com/mr-jums/web .;
  docker push registry.heroku.com/mr-jums/web;
  fi
deploy:
  provider: s3
  access_key_id: AKIAJFY6JWIO3IB4QN2Q
  secret_access_key:
    secure: irp4pX1Mfw4UP9j4yAtuH7jIoK+TuBklRx9WDcipbmmGVFqvxTG3OVOyrVqjQbgbl8HNQejGXhuxBsZtaLr6kp4Fpsym9b0OODzOBJLocz/1PzMJSB6GWhklty8WC4wcGpBT7Y7T4Lzg3pT1hy2NFLALfNoZPP/AQdnnbtePkdqWqjOSQ9RhVTMDoqsKkeM1DPgf0KfTTB4WBlLUVTB1hxipX+0rRARMkgGV5Q7d2BiJjbgsfh21DhRGpdkMUpp+71Udt7dgqHRjnzNV2E1n+tJThjn6HMAxlhLcCWla0Af6nrUOEj489Ci0sLbT526R9156OtGwuCXkFBw7gefngbCC8v6Dz/zLMFOJQeDoId4TUvND9ZRbxexxvfpCeuNc3hdReXlYkhuI0k3d9DKPB1yzVZ2qQMQK7jx5O8iN9fEOjKpPDWb0hMqU8lFQH31vx8zl0rQN9RZAgrI77RQBRVXKjNWTqiShTvOhzvCZm/WUc2LhvD0cruT732sFAErQ3ZBEqSl9UNJPM+2cyKQX6hyDf+1XelKghmwPMGoziptvGSN6Y9rrPbWptoAHkH08uu58GZiFrjFzWLOFVIU4v3gz9Y4gLLOhtCUzqmP78Tl9GNd0ohZj48MVvOIkQL+8XgE+JvijmJu5usasdxU7iZRMXcsRoQ2sLm/Xl2WoP60=
  bucket: mr-jums.bouzuya.net
  local-dir: public/scripts
  upload-dir: scripts
  region: ap-northeast-1
  skip_cleanup: true
  on:
    branch: master
    repo: bouzuya/mr-jums
