language: node_js
node_js:
- node
- '6'
- '5'
deploy:
  provider: heroku
  api_key:
    secure: CwQNvNHlALV0QCg/Nef45iqDlsMwx6ANZ4Mj7SvFpYN0lrziA2IBqQB61k9sH+IBOPR8NMKcC8PEH/HY6Vevk7dMEXOCXc21vYOzNgpxH7CZZrDAbvC9Q/lE8ZZzGmynSciQnSOcKiYRs5AHDVYZQE3RxBHODP3tfTZ1I81KEaLRpc8lxI6CxYlLcj1B8CpgTcWNb8LAJB45tTX9IL5nrO8pP/CrkG0QHw5//K6tQdiyJF5J6Xh+6AP54AnxhHUkjFv8FXz3wBVaifI5rYSDbF3cRFISZzE8hnIN4PmdWkbCaG0HIuIe4r2l21+++qboM7FI5LG+/gIGnA2YdrYs0twfeJIbQT/KK74YOm3Tjxof61Dm5cc4/rmiw5EQuUYavwF7TIIDNCpsK4EHhkhmXXov4WeZW3uSMaPdXnb1h/0hVzXgUV3xSQR3dvk4F+X3jIYFbMNmhKDEX/gA0Z/A04hn/ypqIyh0aljkJlKdgZJE5lbzf5fzH4mbd82bhjQyTGKhmUr4O6oFWMmVVIgl4Uzb8sEiR1QVvcnYdXPXgLbGG4Nm+Ur3FTrUTRtuiHyIPuqs0e5NXVnJBl5nf2xYsjxnZ5kr7qaA3GIsu5SNys3+fnhaChpMH7TBWjNu4P5cJjaWsbYwbKCWGzE8OozRizdXkQtIJh3CDF07Fz6a+xg=
  app: fast-citadel-97475
  on: master
